package com.novax.leadora.infrastructure.persistence.entity.enums;

public enum ActivityLogType {
    LEAD_CREATED,
    LEAD_STATUS_UPDATED,
    LEAD_CONVERTED,
    DEAL_CREATED,
    DEAL_STAGE_UPDATED,
    DEAL_AUTO_WON,
    QUOTATION_CREATED,
    QUOTATION_SUBMITTED,
    QUOTATION_APPROVED,
    QUOTATION_REJECTED,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    TASK_CREATED,
    TASK_COMPLETED,
    LEAD_UPDATED,
    DEAL_UPDATED,
    QUOTATION_UPDATED,
    BOOKING_UPDATED
}
