export const ROUTE_PATHS = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  feedback: "/feedback",
  dashboard: "/dashboard",
  identityAccess: "/identity-access",
  customerFeedback: "/customer-feedback",
  leads: "/leads",
  leadDetail: (id: string) => `/leads/${id}`,
  customerProfiles: "/customer-profiles",
  followUpTasks: "/follow-up-tasks",
  salesPipeline: "/sales-pipeline",
  deals: "/deals",
  interactionTimeline: "/interaction-timeline",
  quotations: "/quotations",
  notifications: "/notifications",
  reminders: "/reminders",
  sla: "/sla",
  bookingConfirmation: "/booking-confirmation",
  reservationStatus: "/reservation-status",
  operationalHandover: "/operational-handover",
  depositPayment: "/deposit-payment",
  frontOfficeHandover: "/front-office-handover",
  reporting: "/reporting",
  aiAssistant: "/ai-assistant",
} as const;
