export const ROUTE_PATHS = {
  login: "/login",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  feedback: "/feedback",
  dashboard: "/dashboard",
  dashboardStaff: "/dashboard/staff",
  dashboardManager: "/dashboard/manager",
  dashboardAdmin: "/dashboard/admin",
  identityAccess: "/identity-access",
  customerFeedback: "/customer-feedback",
  leads: "/leads",
  leadDetail: (id: string) => `/leads/${id}`,
  customerProfiles: "/customer-profiles",
  followUpTasks: "/follow-up-tasks",
  manageFollowUpTasks: "/manage-follow-up-tasks",
  salesPipeline: "/sales-pipeline",
  deals: "/deals",
  interactionTimeline: "/interaction-timeline",
  quotations: "/quotations",
  quotationCreate: "/quotations/create",
  // No page exists at /quotations/[id] — using this 404s. Route to `quotations`
  // (with a highlight param) or `quotationRevise` instead.
  quotationDetail: (id: string) => `/quotations/${id}`,
  quotationRevise: (id: string) => `/quotations/${id}/revise`,
  pendingApprovals: "/quotations/pending-approvals",
  notifications: "/notifications",
  reminders: "/reminders",
  sla: "/sla",
  bookingConfirmation: "/booking-confirmation",
  reservationStatus: "/reservation-status",
  operationalHandover: "/operational-handover",
  depositPayment: "/deposit-payment",
  frontOfficeHandover: "/front-office-handover",
  reporting: "/reporting",
  aiAssistant: "/ai-assistant",
  profile: "/profile",
} as const;
