package com.novax.leadora.application.usecase.reporting;

import com.novax.leadora.api.dto.request.SaveReportLogRequest;
import com.novax.leadora.api.dto.response.ReportLogResponse;
import com.novax.leadora.infrastructure.persistence.entity.NotificationEntity;
import com.novax.leadora.infrastructure.persistence.entity.ReportGenerationLogEntity;
import com.novax.leadora.infrastructure.persistence.entity.UserEntity;
import com.novax.leadora.infrastructure.persistence.repository.NotificationRepository;
import com.novax.leadora.infrastructure.persistence.repository.ReportGenerationLogRepository;
import com.novax.leadora.infrastructure.persistence.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;

@Slf4j
@Service
@RequiredArgsConstructor
public class SaveReportLogUseCase {

    private static final Set<String> STAFF_ROLES = Set.of("SALES", "SALES_STAFF");

    private final ReportGenerationLogRepository reportLogRepository;
    private final UserRepository userRepository;
    private final NotificationRepository notificationRepository;

    @Transactional
    public ReportLogResponse execute(SaveReportLogRequest request) {
        ReportGenerationLogEntity logEntry = ReportGenerationLogEntity.builder()
                .generatedByName(request.getGeneratedByName())
                .generatedByRole(request.getGeneratedByRole())
                .filterDateFrom(request.getFilterDateFrom())
                .filterDateTo(request.getFilterDateTo())
                .filterRoomType(request.getFilterRoomType())
                .filterDiscountThreshold(request.getFilterDiscountThreshold())
                .resultCount(request.getResultCount())
                .action(request.getAction() != null ? request.getAction() : "GENERATE_DISCOUNT_REPORT")
                .result(request.getResult() != null ? request.getResult() : (request.getResultCount() > 0 ? "SUCCESS" : "NO_DATA"))
                .reason(request.getReason())
                .build();

        ReportGenerationLogEntity saved = reportLogRepository.save(logEntry);

        // UC-14.2 step 5: a discount-exceeding report generated by Sales Staff must
        // also reach the Sales Manager, not just sit in the audit log.
        String role = request.getGeneratedByRole();
        if (role != null && STAFF_ROLES.contains(role.toUpperCase())
                && request.getResultCount() != null && request.getResultCount() > 0) {
            try {
                List<UserEntity> managers = userRepository.findByRoleName("MANAGER");
                String message = request.getGeneratedByName() + " generated a discount report with "
                        + request.getResultCount() + " quotation(s) exceeding the "
                        + request.getFilterDiscountThreshold() + "% threshold.";
                for (UserEntity manager : managers) {
                    notificationRepository.save(NotificationEntity.builder()
                            .user(manager)
                            .title("Discount Report Generated")
                            .message(message)
                            .type("DISCOUNT_REPORT_GENERATED")
                            .relatedEntity("REPORT_LOG")
                            .relatedId(saved.getLogId())
                            .build());
                }
            } catch (Exception e) {
                log.warn("Manager notification failed for report log {}: {}", saved.getLogId(), e.getMessage());
            }
        }

        return ReportLogResponse.from(saved);
    }

    /**
     * POST-2 (UC-23.1 / UC-23.2) — audit a report VIEW action (who, when, which report, filters,
     * how many records). Runs in its own transaction asynchronously: an audit-log failure must
     * never break the report the user asked for, so callers wrap this and swallow exceptions.
     */
    @Async("taskExecutor")
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void logReportView(String actorName, String actorRole, String action,
                              LocalDate from, LocalDate to, int resultCount) {
        ReportGenerationLogEntity logEntry = ReportGenerationLogEntity.builder()
                .generatedByName(actorName != null ? actorName : "Unknown")
                .generatedByRole(actorRole)
                .filterDateFrom(from)
                .filterDateTo(to)
                .resultCount(resultCount)
                .action(action)
                .result(resultCount > 0 ? "SUCCESS" : "NO_DATA")
                .build();
        reportLogRepository.save(logEntry);
    }
}
